package Kerntaal.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {

  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Context_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Gebeurtenistype_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Objectivering_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ObjecttypeRef_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Omstandigheidstype_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Rol_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }
  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0c, descriptor.getConceptFqName())) {
      case 0:
        if ("Kerntaal.editor.Feittype_EditorComponent".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new Feittype_EditorComponent());
        }
        break;
      default:
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }


  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"Kerntaal.structure.Context", "Kerntaal.structure.Gebeurtenistype", "Kerntaal.structure.Objectivering", "Kerntaal.structure.ObjecttypeRef", "Kerntaal.structure.Omstandigheidstype", "Kerntaal.structure.Rol"};
  private static String[] stringSwitchCases_xbvbvu_a0a0c = new String[]{"Kerntaal.structure.Feittype"};
}
