package Kerntaal.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptContext = new ConceptDescriptorBuilder("Kerntaal.structure.Context", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1aca1L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(7238244235573570726L, "objecttype", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1829bL), true, true, false), new ConceptDescriptorBuilder.Link(7238244235573570724L, "feittype", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1828fL), true, true, false)).children(new String[]{"objecttype", "feittype"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptFeittype = new ConceptDescriptorBuilder("Kerntaal.structure.Feittype", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1828fL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(7238244235573559957L, "rol", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae18294L), true, true, false)).children(new String[]{"rol"}, new boolean[]{true}).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptGebeurtenistype = new ConceptDescriptorBuilder("Kerntaal.structure.Gebeurtenistype", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1cdd1L)).super_("Kerntaal.structure.Feittype").super_(MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1828fL)).parents("Kerntaal.structure.Feittype").parentIds(MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1828fL)).alias("gebeurtenis", "").create();
  /*package*/ final ConceptDescriptor myConceptObjectivering = new ConceptDescriptorBuilder("Kerntaal.structure.Objectivering", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x4d3c3d745657b668L)).super_("Kerntaal.structure.TypeRef").super_(MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x4d3c3d745657edacL)).parents("Kerntaal.structure.TypeRef").parentIds(MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x4d3c3d745657edacL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(5565390809397184753L, "feittype", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1828fL), false)).references("feittype").create();
  /*package*/ final ConceptDescriptor myConceptObjecttype = new ConceptDescriptorBuilder("Kerntaal.structure.Objecttype", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1829bL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();
  /*package*/ final ConceptDescriptor myConceptObjecttypeRef = new ConceptDescriptorBuilder("Kerntaal.structure.ObjecttypeRef", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x4d3c3d745657edb8L)).super_("Kerntaal.structure.TypeRef").super_(MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x4d3c3d745657edacL)).parents("Kerntaal.structure.TypeRef").parentIds(MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x4d3c3d745657edacL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(5565390809397194169L, "objecttype", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1829bL), false)).references("objecttype").create();
  /*package*/ final ConceptDescriptor myConceptOmstandigheidstype = new ConceptDescriptorBuilder("Kerntaal.structure.Omstandigheidstype", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1cdfbL)).super_("Kerntaal.structure.Feittype").super_(MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1828fL)).parents("Kerntaal.structure.Feittype").parentIds(MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae1828fL)).alias("omstandigheid", "").create();
  /*package*/ final ConceptDescriptor myConceptRol = new ConceptDescriptorBuilder("Kerntaal.structure.Rol", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x647368c84ae18294L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(5565390809397194157L, "type", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x4d3c3d745657edacL), false, false, false)).children(new String[]{"type"}, new boolean[]{false}).create();
  /*package*/ final ConceptDescriptor myConceptTypeRef = new ConceptDescriptorBuilder("Kerntaal.structure.TypeRef", MetaIdFactory.conceptId(0xebc25b10cc844e74L, 0xbdce2dc8d9e066b3L, 0x4d3c3d745657edacL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptContext, myConceptFeittype, myConceptGebeurtenistype, myConceptObjectivering, myConceptObjecttype, myConceptObjecttypeRef, myConceptOmstandigheidstype, myConceptRol, myConceptTypeRef);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0n, conceptFqName)) {
      case 0:
        return myConceptContext;
      case 1:
        return myConceptFeittype;
      case 2:
        return myConceptGebeurtenistype;
      case 3:
        return myConceptObjectivering;
      case 4:
        return myConceptObjecttype;
      case 5:
        return myConceptObjecttypeRef;
      case 6:
        return myConceptOmstandigheidstype;
      case 7:
        return myConceptRol;
      case 8:
        return myConceptTypeRef;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0n = new String[]{"Kerntaal.structure.Context", "Kerntaal.structure.Feittype", "Kerntaal.structure.Gebeurtenistype", "Kerntaal.structure.Objectivering", "Kerntaal.structure.Objecttype", "Kerntaal.structure.ObjecttypeRef", "Kerntaal.structure.Omstandigheidstype", "Kerntaal.structure.Rol", "Kerntaal.structure.TypeRef"};
}
