package Kerntaal.behavior;

/*Generated by MPS */


public class Gebeurtenistype_BehaviorDescriptor extends Feittype_BehaviorDescriptor {
  public Gebeurtenistype_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Kerntaal.structure.Gebeurtenistype";
  }
}
