package Kerntaal.behavior;

/*Generated by MPS */


public class Omstandigheidstype_BehaviorDescriptor extends Feittype_BehaviorDescriptor {
  public Omstandigheidstype_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Kerntaal.structure.Omstandigheidstype";
  }
}
